Try to be more POSIX-y?
`if ! command` appears to be invalid
(https://travis-ci.org/git-tfs/git-tfs/builds/18484621)

diff --git a/script/travis b/script/travis
--- a/script/travis
+++ b/script/travis
@@ -1,10 +1,9 @@
 #!/bin/sh -x
 
-if ! git submodule update --init --recursive
-then
-  exit 1
-fi
+# Exit on error
+set -e
 
+git submodule update --init --recursive
 git submodule foreach --recursive git clean -f -x -d
 
 LIBGIT2SHA=`cat lib/libgit2sharp/LibGit2Sharp/libgit2_hash.txt`
@@ -12,19 +11,10 @@ SHORTSHA=`echo $LIBGIT2SHA | cut -c 1-7`
 
 mkdir lib/libgit2sharp/cmake-build
 cd lib/libgit2sharp/cmake-build
-if ! cmake -DTHREADSAFE=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_CLAR=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=./libgit2-bin -DLIBGIT2_FILENAME=git2-$SHORTSHA ../libgit2
-then
-  exit 2
-fi
-if ! cmake --build . --target install
-then
-  exit 3
-fi
+cmake -DTHREADSAFE=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_CLAR=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=./libgit2-bin -DLIBGIT2_FILENAME=git2-$SHORTSHA ../libgit2
+cmake --build . --target install
 
 export LD_LIBRARY_PATH=$PWD/libgit2-bin/lib
 
 cd ../../..
-if ! xbuild CI.proj
-then
-  exit 5
-fi
+xbuild CI.proj
